export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const HANDLE_CHANGE_CANDIDATE = 'HANDLE_CHANGE_CANDIDATE'
export const HANDLE_CHANGE_COURSE = 'HANDLE_CHANGE_COURSE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR'

export const CREATE_CANDIDATE_BEGIN = 'CREATE_CANDIDATE_BEGIN'
export const CREATE_CANDIDATE_SUCCESS = 'CREATE_CANDIDATE_SUCCESS'
export const CREATE_CANDIDATE_ERROR = 'CREATE_CANDIDATE_ERROR'

export const CREATE_COURSE_BEGIN = 'CREATE_COURSE_BEGIN'
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS'
export const CREATE_COURSE_ERROR = 'CREATE_COURSE_ERROR'

export const GET_JOBS_BEGIN = 'GET_JOBS_BEGIN'
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS'
export const GET_CANDIDATES_BEGIN = 'GET_CANDIDATES_BEGIN'
export const GET_CANDIDATES_SUCCESS = 'GET_CANDIDATES_SUCCESS'
export const GET_COURSES_BEGIN = 'GET_COURSES_BEGIN'
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS'

export const SET_EDIT_JOB = 'SET_EDIT_JOB'
export const SET_EDIT_CANDIDATE = 'SET_EDIT_CANDIDATE'
export const SET_EDIT_COURSE = 'SET_EDIT_COURSE'
export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN'
export const DELETE_CANDIDATE_BEGIN = 'DELETE_CANDIDATE_BEGIN'
export const DELETE_COURSE_BEGIN = 'DELETE_COURSE_BEGIN'

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN'
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS'
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR'

export const EDIT_CANDIDATE_BEGIN = 'EDIT_CANDIDATE_BEGIN'
export const EDIT_CANDIDATE_SUCCESS = 'EDIT_CANDIDATE_SUCCESS'
export const EDIT_CANDIDATE_ERROR = 'EDIT_CANDIDATE_ERROR'

export const EDIT_COURSE_BEGIN = 'EDIT_COURSE_BEGIN'
export const EDIT_COURSE_SUCCESS = 'EDIT_COURSE_SUCCESS'
export const EDIT_COURSE_ERROR = 'EDIT_COURSE_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const CHANGE_PAGE = 'CHANGE_PAGE'
export const CHANGE_PAGE_CANDIDATE = 'CHANGE_PAGE_CANDIDATE'
export const CHANGE_PAGE_COURSE = 'CHANGE_PAGE_COURSE'